core/mysite/common/urls.py
from django.conf.urls import url
from common import views
from django.contrib.auth import views as auth_views

app_name = 'common'


urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^login/$', views.login_crm, name="login"),
    url(r'^signup/$', views.sign_up, name="sign_up"),
    url(r'^logout/$', views.logout_crm, name="logout"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^users/list$', views.users_list, name="users_list"),
    url(r'^users/create$', views.create_user, name="create_user"),
    url(r'^users/(?P<user_id>\d*)/view/$', views.view_user, name="view_user"),
    url(r'^users/(?P<user_id>\d*)/edit/$', views.edit_user, name="edit_user"),
    url(r'^user/(?P<user_id>\d*)/delete/$', views.remove_user, name="remove_user"),

   ]

core/mysite/dasein/urls.py
from django.conf.urls import url
from dasein import views

app_name = 'dasein'


urlpatterns = [
    url(r'^$', views.list_zone, name="list_zone"),
    url(r'^update/$', views.update, name="update"),
    url(r'^create/$', views.create_zone, name="create_zone"),
    url(r'^(?P<pk>[-\w]+)/edit/$', views.edit_zone, name="edit_zone"),
    url(r'^(?P<pk>[-\w]+)/remove/$', views.remove_zone, name="remove_zone"),
    url(r'^(?P<pk>[-\w]+)/$', views.view_zone, name="view_zone"),
   ]

core/mysite/mysite/urls.py
from django.urls import include, path
from django.conf.urls import include, url

from django.contrib import admin

urlpatterns = [
    url(r'', include('common.urls')),
    url(r'^dasein/', include('dasein.urls')),
    url(r'^admin/', admin.site.urls),
]

core/mysite/common/forms.py
from django import forms
from django.contrib.auth import authenticate

from common.models import User


class UserForm(forms.ModelForm):

    password = forms.CharField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ['email', 'username',]

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        self.fields['username'].required = True
        self.fields['email'].required = True

        if not self.instance.pk:
            self.fields['password'].required = True

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password) < 4:
                raise forms.ValidationError(
                    'Password must be at least 4 characters long!')
        return password

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if self.instance.id:
            if self.instance.email != email:
                if not User.objects.filter(email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
                else:
                    raise forms.ValidationError('Email already exists')
            else:
                return self.cleaned_data.get("email")
        else:
            if not User.objects.filter(email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
            else:
                raise forms.ValidationError('User already exists with this email')


class LoginForm(forms.ModelForm):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            self.user = authenticate(email=email, password=password)
            if self.user:
                if not self.user.is_active:
                    raise forms.ValidationError("User is Inactive")
            else:
                raise forms.ValidationError("Invalid email and password")
        return self.cleaned_data


class SignUpForm(forms.ModelForm):

    email = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control",})
    )


    # phone = forms.CharField(widget=forms.TextInput(
    #     attrs={'class': "form-control", "placeholder" : "+1(222)917-3344"})
    # )

    password = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control", "type" : "password"}),
        max_length=100,
        required=False,
    )

    class Meta:
        model = User
        fields = ['email']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['email'].required = True

        if not self.instance.pk:
            self.fields['password'].required = True

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password) < 4:
                raise forms.ValidationError(
                    'Password must be at least 4 characters long!')
        return password

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if self.instance.id:
            if self.instance.email != email:
                if not User.objects.filter(email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
                else:
                    raise forms.ValidationError('Email already exists')
            else:
                return self.cleaned_data.get("email")
        else:
            if not User.objects.filter(email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
            else:
                raise forms.ValidationError('User already exists with this email')

core/mysite/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dasein App</title>

    <link rel="stylesheet" href="{% static 'vendors/iconfonts/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.addons.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/iconfonts/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extralinks %} {% endblock %}

    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
</head>

<body>
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row" style="background: #00a0ff!important;">
      <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
        <a class="navbar-brand brand-logo" href="{% url 'dasein:list_zone' %}">
          <!-- <img src="{% static 'images/logo.png' %}" style="height: auto; max-width: 350px;" alt="logo" /> -->
          <h2 style="color: black; line-height: 60px;">Dasein</h2>
        </a>
        <a class="navbar-brand brand-logo-mini" href="{% url 'dasein:list_zone' %}">
          <!-- <img src="{% static 'images/logo-mini.png' %}" alt="logo" /> -->
          <p  style="color: black">Dasein</p>
        </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center">
       
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown d-none d-xl-inline-block">
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="{% url 'common:profile' %}" data-toggle="dropdown" aria-expanded="false">
              <span class="profile-text">{{ request.user }}</span>
              <img class="img-xs rounded-circle" src="http://conceptsoft.co.uk/wp-content/uploads/2015/07/icon-user-default.png" alt="Profile image">
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              <a class="dropdown-item mt-2" href="{% url 'common:profile' %}">
                Profile
              </a>
              <a class="dropdown-item" href="{% url 'common:logout' %}">
                Sign Out
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item nav-profile">
            <div class="nav-link">
              <div class="user-wrapper">
                <div class="profile-image">
                  <img src="http://conceptsoft.co.uk/wp-content/uploads/2015/07/icon-user-default.png" alt="profile image">
                </div>
                <div class="text-wrapper">
                  <p class="profile-name">{{ request.user }}</p>
                  <div>
                    <span class="status-indicator online"></span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="nav-item {{ clients }}">
            <a class="nav-link" id="accounts" href="{% url 'dasein:list_zone' %}">
              <i class="menu-icon mdi mdi-account-card-details"></i>
              <span class="menu-title">Zones</span>
            </a>
          </li>
          <li class="nav-item {{ tts }}">
            <a class="nav-link" id="tools" href="{% url 'dasein:create_zone' %}">
              <i class="menu-icon mdi mdi-chart-line"></i>
              <span class="menu-title">New Zone</span>
            </a>
          </li>
          <li class="nav-item {{ blog }}">
            <a class="nav-link" id="tools" href="/tools">
              <i class="menu-icon mdi mdi-format-text"></i>
              <span class="menu-title">About Us</span>
            </a>
          </li>
         <!--  <li class="nav-item {{ seo }}">
            <a class="nav-link" id="tools" href="/tools">
              <i class="menu-icon mdi mdi-search-web"></i>
              <span class="menu-title">SEO</span>
            </a>
          </li> -->
         {% if request.user.is_superuser %}
          <li class="nav-item {{ users_nav }}">
            <a class="nav-link" id="users" href="{% url 'common:users_list' %}">
              <i class="menu-icon mdi mdi-account-multiple"></i>
              <span class="menu-title">Users</span>
            </a>
          </li>
          {% endif %}
          <li class="nav-item {{ profile }}">
            <a class="nav-link" id="users" href="{% url 'common:profile' %}">
              <i class="menu-icon mdi mdi-account"></i>
              <span class="menu-title">Profile</span>
            </a>
          </li>
        </ul>
      </nav>
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper" id="mainbody">
          {% block breadcrumb %}
        {% endblock %}
        <!-- breadcrumb ends here -->
        {% block content %}
        {% endblock %}
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'vendors/js/vendor.bundle.addons.js' %}"></script>
  <!-- endinject -->
  <script src="{% static 'js/off-canvas.js' %}"></script>
  <script src="{% static 'js/misc.js' %}"></script>
  <script src="{% static 'js/dashboard.js' %}"></script>
  <!-- End custom js for this page-->

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment-with-locales.min.js"></script>
<script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
</body>

core/mysite/templates/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<form id="add_form" method="POST" action="" novalidate>
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
         <div class="card-title">
          Change Passowrd
        </div>
          <div class="row marl no-gutters">
            <div class="col-md-12">
         
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Old Password</label>
                  <input type="password" class="form-control" name="CurrentPassword" value="{{request.POST.CurrentPassword}}">
                </div>
                <span class="error">{{ errors.CurrentPassword }}</span>
                {% if error %}
                <span class="error">{{error}}</span>
                {% endif %}
              </div>
              {% endif %}
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">New Password</label>
                  <input type="password" class="form-control" name="Newpassword" value="{{request.POST.Newpassword}}">
                </div>
                <span class="error">{{ errors.Newpassword }}</span>
              </div>
              {% endif %}
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Confirm New Password</label>
                  <input type="password" class="form-control" name="confirm" value="{{request.POST.confirm}}">
                </div>
                <span class="error">{{ errors.confirm }}</span>
              </div>
              {% endif %}
            </div>
          </div>
          <br>
          <div class="row marl buttons_row form_btn_row text-center">
            <button class="btn btn-default save" type="submit">Change Password</button>
            <button class="btn btn-default" type="reset">Cancel</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock content %}

core/mysite/templates/forgot_password.html
{% load staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django CRM</title>
    <!-- Bootstrap core CSS -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    <!-- Custom styling plus plugins -->
    {% compress css %}
      <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %}{% endblock %}
</head>
<body class="login_register_body">
<div class="container">
    <div class="row marl justify-content-center login_row">
        <div class="col-md-6 col-lg-6 col-xl-4">
            <div class="login_block">
                <div class="login_form_block">
                    <div class="welcome">Forgot Password?</div>
                    <form method="POST" action="">
                        <div class="form-group">
                            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
                        </div>
                        
                        <div class="forgot">Back to login <a href="/login/">Click Here?</a></div>
                        <button type="submit" class="btn btn-danger">Reset Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

core/mysite/templates/index.html
{% extends 'base.html' %}
      <a href="/logout/"><button class="btn btn-primary" type="button">Logout</button></a

core/mysite/templates/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content%}
<!-- OPPORTUNITY VIEW STARTS -->
  <div class="main_container" id="maincontainer">
    <div class="overview_form_block row marl justify-content-center">
      <div class="col-md-10">
        <div class="card">
          
          <div class="card-body" id="datashow">
            <div class="row mx-auto">
              <div class="col-6">
                <h5 style="">Profile</h5>
              </div>
              <div class="col-6" style="text-align: right;">
                <a href="{% url 'common:edit_user' user_obj.id %}" class="btn btn-success edit">Edit</a>
              </div>
            </div>
            <div class="row marl no-gutters">
              <div class="col-md-8">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_name" data-name="name">Name</label>
                    <div class="contact_field" id="contact_name" data-name="name">{{ user_obj.first_name }} {{ user_obj.last_name }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_contact_account" data-name="name">UserName</label>
                    <div class="contact_field" id="contact_account" data-name="name">{{ user_obj.username }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_email" data-name="name">Email</label>
                    <div class="contact_field" id="contact_email" data-name="name">{{ user_obj.email }}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- OPPORTUNITY VIEW ENDS -->
{% endblock %}

core/mysite/templates/registration.html
{% extends 'base.html' %}
{% block content %}
<h1>Registration</h1>
    <form method="POST" class="user-form">
        {{ reg_form.as_p }}
        <button class="btn btn-primary" type="submit">Submit</button></form>
{% endblock %}

core/mysite/templates/zone_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content%}

<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.css' rel='stylesheet' />
<style>
    body { margin:0; padding:0; }
    #map { position:relative; height: 500px; width: 100%; }
</style>



<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v3.0.11/turf.min.js'></script>
<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v1.0.9/mapbox-gl-draw.js'></script>
<link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v1.0.9/mapbox-gl-draw.css' type='text/css'/>


<!-- OPPORTUNITY VIEW STARTS -->
  <div class="main_container" id="maincontainer">
    <div class="overview_form_block row marl justify-content-center">
      <div class="col-md-6">
        <div class="card">
          
          <div class="card-body" id="datashow">
            <div class="row mx-auto">
              <div class="col-12">

                <div id='map'></div>


              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="card">
          
          <div class="card-body" id="datashow">
            <div class="row mx-auto">
              <div class="col-6" style="padding-left: 0;">
                <h1>{{zone.zone_name}}</h1>
                <br>
              </div>
              <div class="col-6" style="text-align: right;">
                <a href="{% url 'dasein:edit_zone' pk=zone.pk %}" class="btn btn-success edit">Edit</a>
              </div>
            </div>
            <div class="row marl no-gutters">
              <div class="col-md-12">
                  <p>Description:</p>
                  <p>{{ zone.description }}</p>
                  <hr>
                  <p>Statistics:</p>
                  <p>{{ zone.coordinate }}</p>


                    <table id ='myTable'>
                        <thead>
                        <tr>
                          <th width="25%">UUID</th>
                          <th width="25%">Time</th>
                          <th width="25%">Lat</th>
                          <th width="25%">Long</th>
                        </tr>
                        </thead>
                        <tbody >
                        </tbody >        
                    </table>

              </div>
            </div>
          </div>
        </div>
      </div>



    </div>
  </div>

<script>
mapboxgl.accessToken = 'pk.eyJ1IjoiZGVuaXNvbHQ5NSIsImEiOiJjanBlancwM3MwMTBvM3BvNnk0cG93NnE3In0.EV4GsgyWMxN9B6HfJqIfAA';



var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/light-v9', //hosted style id
    center: [37.6173, 55.7558], // starting position
    zoom: 12 // starting zoom
});


map.on('load', function () {

  map.addSource("point", {
        "type": "geojson",
        "data": {
            "type": "FeatureCollection",
            "features": [{
               "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [-77.03238901390978, 38.913188059745586]
    },
    "properties": {
       "title": "Mapbox DC",
       "marker-symbol": "default_marker"
    }

            }]
        }
    });



    map.addLayer({
        'id': 'maine',
        'type': 'fill',
        'source': {
            'type': 'geojson',
            'data': {
                'type': 'Feature',
                'geometry': {
                    'type': 'Polygon',
                    'coordinates': [{{coordinates}}]
                            }

            }
        },
        'layout': {},
        'paint': {
            'fill-color': '#088',
            'fill-opacity': 0.8
        }
    });
});
</script>

<script type="text/javascript">   
    $( document ).ready(function() {
       setInterval(function(){
            $.getJSON('/dasein/update/',
                    function (data) {
                        var json = data['latest_results_list'];
                        console.log(json);
                        var tr;
                         $('#myTable tbody').html("");
                        for (var i = 0; i < json.length; i++) {
                            tr = $('<tr/>');
                            tr.append("<td>" + json[i].uuid + "</td>");
                            tr.append("<td>" + json[i].time + "</td>");
                            tr.append("<td>" + json[i].lat + "</td>");
                            tr.append("<td>" + json[i].long + "</td>");
                             $('#myTable tbody').append(tr);

                        }
                    });
       },3000);
    });

</script>

{% endblock %}

core/mysite/templates/zone_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content%}

<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.css' rel='stylesheet' />
<style>
    body { margin:0; padding:0; }
    #map { position:relative; height: 500px; width: 100%; }
</style>



<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v3.0.11/turf.min.js'></script>
<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v1.0.9/mapbox-gl-draw.js'></script>
<link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v1.0.9/mapbox-gl-draw.css' type='text/css'/>


<!-- OPPORTUNITY VIEW STARTS -->
  <div class="main_container" id="maincontainer">
    <div class="overview_form_block row marl justify-content-center">
      <div class="col-md-6">
        <div class="card">
          
          <div class="card-body" id="datashow">
            <div class="row mx-auto">
              <div class="col-12">

                <div id='map'></div>
                <div class='calculation-box'>
                    <p>Draw a polygon using the draw tools.</p>
                    <div id='calculated-area'></div>
                </div>


              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="card">
          
          <div class="card-body" id="datashow">
            <div class="row mx-auto">
              <div class="col-6" style="padding-left: 0;">
                <h5>Create a Zone</h5>
                <br>
              </div>
              <div class="col-6" style="text-align: right;">
<!--                 <a href="{% url 'common:edit_user' user_obj.id %}" class="btn btn-success edit">Edit</a>
 -->              </div>
            </div>
            <div class="row marl no-gutters">
              <div class="col-md-8">
                <form method="POST" action="">

                {% for field in zone_form %}

                <div class="form-group">

                  <label class="label">{{field.label}}</label>

                  <div class="input-group">
                    {{ field }}
                  </div>
                </div>
                {% endfor %}

                <input type="hidden" id="coordinates" name="coordinates" value="" />

                <p style="color: red;">{{ zone_form.errors }}</p>

                <div class="form-group">
                  <button type="submit" class="btn btn-primary submit-btn btn-block">Submit</button>
                </div>
                
              </form>
              </div>
            </div>
          </div>
        </div>
      </div>



    </div>
  </div>



<script>
mapboxgl.accessToken = 'pk.eyJ1IjoiZGVuaXNvbHQ5NSIsImEiOiJjanBlancwM3MwMTBvM3BvNnk0cG93NnE3In0.EV4GsgyWMxN9B6HfJqIfAA';
/* eslint-disable */
var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/mapbox/light-v9', //hosted style id
    center: [37.6173, 55.7558], // starting position
    zoom: 12 // starting zoom
});

var draw = new MapboxDraw({
    displayControlsDefault: false,
    controls: {
        polygon: true,
        trash: true
    }
});
map.addControl(draw);

map.on('draw.create', updateArea);
map.on('draw.delete', updateArea);
map.on('draw.update', updateArea);

function updateArea(e) {
    var data = draw.getAll();
    var answer = document.getElementById('calculated-area');

    var coord = document.getElementById('coordinates');

    if (data.features.length > 0) {
        var area = turf.area(data);
        //var coordinate = turf.area(data);
        var coordinates = data["features"]["0"]["geometry"]["coordinates"]["0"];
        console.log(coordinates);


        coord.value = coordinates;

        // restrict to area to 2 decimal points
        var rounded_area = Math.round(area*100)/100;
        answer.innerHTML = '<p><strong>' + rounded_area + '</strong> square meters</p>';
    } else {
        answer.innerHTML = '';
        if (e.type !== 'draw.delete') alert("Use the draw tools to draw a polygon!");
    }
}

</script>
{% endblock %}

core/mysite/templates/zone_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<!-- main_container starts here -->
  <!-- heading_create starts here -->
  <div class="row marl heading_create">
    <div class="heading col-md-12">
     <div class="no-gutters row">
      <div class="col-8">
        <h1>Zones</h1>
      </div>
      <div class="col-4">
        <div class="" style="text-align: right;  margin-bottom: 5%;">
          <button style="max-width: 150px;" class="btn btn-success btn-block ml-auto "><a style="color: white;" href="{% url 'dasein:create_zone' %}"> Add New Zone</a></button>
        </div>
      </div>
      </div>
    </div>
  </div>
  <!-- heading_create ends here -->
  <!-- filter_row starts here -->
  <div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
         <div class="panel-heading-list card-title">
         List of Zones
          <span class="float-right total_count">Total Zones {{zones|length}}</span>
        </div>
          <div class="table-responsive">
           <table class="table table-bordered">
            <thead>
              <tr>
                <th width="5%">ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Coordinates</th>
              </tr>
            </thead>
            <tbody>
              {% for zone in zones %}
              <tr class="text-center">
                <td scope="row">{{ forloop.counter }}</td>
                <td><a href="{% url 'dasein:view_zone' pk=zone.pk %}">{{ zone.zone_name }}</a></td>
                <td><a>{{ zone.description }}</a></td>
                <td><a>{{ zone.coordinate|truncatechars:30 }}</a></td>
                <td class="actions">
                  <a href="{% url 'dasein:view_zone' pk=zone.pk %}" class="btn btn-info view"><i class="fas fa-eye"></i></a>
                  <a href="{% url 'dasein:edit_zone' pk=zone.pk %}" style="background-color: #7ED321; border: 0px; color: white;" class="btn btn-success edit"><i class="fas fa-cogs"></i></a>
                  <a href="{% url 'dasein:remove_zone' pk=zone.id %}" style="background-color: #D0021B; border: 0px; color: white;" class="btn btn-danger delete remove_account"><i class="fas fa-trash"></i></a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          </div>
          {% ifequal zones|length 0 %}
            <h6 class="text-center">No Zone Records Found</h6>
          {% endifequal %}
        </div>
      </div>
      <br clear="all">
    </div>
  </div>

{% endblock %}