core/mysite/common/urls.py
from django.conf.urls import url
from common import views
from django.contrib.auth import views as auth_views

app_name = 'common'


urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^login/$', views.login_crm, name="login"),
    url(r'^signup/$', views.sign_up, name="sign_up"),
    url(r'^logout/$', views.logout_crm, name="logout"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^users/list$', views.users_list, name="users_list"),
    url(r'^users/create$', views.create_user, name="create_user"),
    url(r'^users/(?P<user_id>\d*)/view/$', views.view_user, name="view_user"),
    url(r'^users/(?P<user_id>\d*)/edit/$', views.edit_user, name="edit_user"),
    url(r'^user/(?P<user_id>\d*)/delete/$', views.remove_user, name="remove_user"),

   ]

core/mysite/mysite/urls.py
from django.urls import include, path
from django.conf.urls import include, url

from django.contrib import admin

urlpatterns = [
    url(r'', include('common.urls')),
    url(r'^dasein/', include('dasein.urls')),
    url(r'^admin/', admin.site.urls),
]

core/mysite/common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

from django.dispatch import receiver
from django.db.models.signals import post_save

class User(AbstractBaseUser, PermissionsMixin):
	username = models.CharField(max_length=100, unique=True, null=True)
	email = models.EmailField(max_length=255, unique=True)
	date_joined = models.DateTimeField(('date joined'), auto_now_add=True)
	is_staff = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)
	is_admin = models.BooleanField(default=False)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username', ]

	objects = UserManager()

	def __unicode__(self):
		return self.email

@receiver(post_save, sender=User)
def create_base64_str(sender, instance=None, created=False, **kwargs):
    if created:
        instance.username = str(instance.pk)
        instance.save()

core/mysite/common/forms.py
from django import forms
from django.contrib.auth import authenticate

from common.models import User


class UserForm(forms.ModelForm):

    password = forms.CharField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ['email', 'username',]

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        self.fields['username'].required = True
        self.fields['email'].required = True

        if not self.instance.pk:
            self.fields['password'].required = True

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password) < 4:
                raise forms.ValidationError(
                    'Password must be at least 4 characters long!')
        return password

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if self.instance.id:
            if self.instance.email != email:
                if not User.objects.filter(email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
                else:
                    raise forms.ValidationError('Email already exists')
            else:
                return self.cleaned_data.get("email")
        else:
            if not User.objects.filter(email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
            else:
                raise forms.ValidationError('User already exists with this email')


class LoginForm(forms.ModelForm):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            self.user = authenticate(email=email, password=password)
            if self.user:
                if not self.user.is_active:
                    raise forms.ValidationError("User is Inactive")
            else:
                raise forms.ValidationError("Invalid email and password")
        return self.cleaned_data


class SignUpForm(forms.ModelForm):

    email = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control",})
    )


    # phone = forms.CharField(widget=forms.TextInput(
    #     attrs={'class': "form-control", "placeholder" : "+1(222)917-3344"})
    # )

    password = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control", "type" : "password"}),
        max_length=100,
        required=False,
    )

    class Meta:
        model = User
        fields = ['email']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['email'].required = True

        if not self.instance.pk:
            self.fields['password'].required = True

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password) < 4:
                raise forms.ValidationError(
                    'Password must be at least 4 characters long!')
        return password

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if self.instance.id:
            if self.instance.email != email:
                if not User.objects.filter(email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
                else:
                    raise forms.ValidationError('Email already exists')
            else:
                return self.cleaned_data.get("email")
        else:
            if not User.objects.filter(email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
            else:
                raise forms.ValidationError('User already exists with this email')

core/mysite/common/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.http.response import Http404
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.hashers import check_password


from common.models import User
from common.forms import UserForm, LoginForm, SignUpForm


def admin_required(function):

    def wrapper(request, *args, **kwargs):
        user = request.user
        if user.is_authenticated:
            if user.is_superuser:
                return function(request, *args, **kwargs)
            else:
                raise Http404
        else:
            return redirect("common:login")
    return wrapper


@login_required
def home(request):
    return render(request, 'index.html')



@login_required
def profile(request):
    profile = "active"
    user = request.user
    user_obj = User.objects.get(id=user.id)
    return render(request, "profile.html", {'user_obj': user_obj, 'profile' : profile})


def login_crm(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        form = LoginForm(request.POST, request=request)
        if form.is_valid():
            user = authenticate(username=request.POST.get('email'), password=request.POST.get('password'))
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    return render(request, "login.html", {"error": True, "message": "Your Account is InActive. Please Contact Administrator"})
            else:
                return render(request, "login.html", {"error": True, "message": "Your Account is not Found. Please Contact Administrator"})
        else:
            return render(request, "login.html", {"error": True, "message": "Your username and password didn't match. Please try again."})
    return render(request, 'login.html')


def forgot_password(request):
    return render(request, 'forgot_password.html')


def logout_crm(request):
    logout(request)
    request.session.flush()
    return redirect("common:login")


@admin_required
def users_list(request):
    users_nav = "active"
    users_list = User.objects.all()
    page = request.POST.get('per_page')
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    username = request.POST.get('username')
    email = request.POST.get('email')
    active_users = User.objects.filter(is_active=True)
    inactive_users = User.objects.filter(is_active=False)
    if first_name:
        users_list = users_list.filter(first_name__icontains=first_name)
    if last_name:
        users_list = users_list.filter(last_name__icontains=last_name)
    if username:
        users_list = users_list.filter(username__icontains=username)
    if email:
        users_list = users_list.filter(email__icontains=email)
    return render(request, "list.html", {
        'users': users_list, 'active_users': active_users,
        'per_page': page, 'inactive_users': inactive_users,
        'users_nav' : users_nav,
    })


@admin_required
def create_user(request):
    user_form = UserForm()
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            if request.POST.get("password"):
                user.set_password(request.POST.get("password"))
            user.save()
            return redirect("common:users_list")
        else:
            return render(request, 'create.html', {'user_form': user_form, "errors": user_form.errors})
    else:
        return render(request, 'create.html', {'user_form': user_form})


@admin_required
def view_user(request, user_id):
    users_list = User.objects.all()
    user_obj = User.objects.filter(id=user_id)
    active_users = User.objects.filter(is_active=True)
    inactive_users = User.objects.filter(is_active=False)
    return render(request, "list.html", {
        'users': users_list, 'user_obj': user_obj,
        'active_users': active_users, 'inactive_users': inactive_users
    })


def edit_user(request, user_id):
    user_obj = get_object_or_404(User, id=user_id)
    user_form = UserForm(instance=user_obj)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user_obj)
        if user_form.is_valid():
            user_form.save()
            return redirect("common:profile")
        else:
            return render(request, 'create.html', {'user_form': user_form, "errors": user_form.errors})
    else:
        return render(request, 'create.html', {'user_form': user_form, 'user_obj': user_obj})


@admin_required
def remove_user(request, user_id):
    user_obj = get_object_or_404(User, id=user_id)
    user_obj.delete()
    return redirect("common:users_list")


def sign_up(request):
    user_form = SignUpForm()
    if request.method == 'POST':
        user_form = SignUpForm(request.POST)
        print("try")
        if user_form.is_valid():
            print("YO")
            user = user_form.save(commit=False)
            if request.POST.get("password"):
                user.set_password(request.POST.get("password"))
            user.save()
            return redirect("common:home")
        else:
            return render(request, 'signup.html', {'user_form': user_form, "errors": user_form.errors})
    else:
        return render(request, 'signup.html', {'user_form': user_form})

# from django.shortcuts import render
# from django.http import HttpResponse
# import pyrebase
# from django.contrib import auth
# import time

# config = {
#   "apiKey": "AIzaSyBQ8MJ9C3QZlBMqQJkjyd6-JFbY4j0ldpw",
#   "authDomain": "dasein-e0028.firebaseapp.com",
#   "databaseURL": "https://dasein-e0028.firebaseio.com",
#   "storageBucket": "dasein-e0028.appspot.com",
#   "messagingSenderId": "835924764891",
# }

# firebase = pyrebase.initialize_app(config)
# database=firebase.database()
# storage=firebase.storage()
# authen = firebase.auth()

# def index(request):
# 	return render(request,'adx/index.html')

# def about(request):
# 	return render(request,'adx/about.html')

# def signIn(request):
# 	return render(request, "adx/signIn.html")

# def post_signin(request):
# 	email=request.POST.get('email')
# 	passw = request.POST.get("pass")
# 	try:
# 		user = auth.refresh(user['refreshToken'])
# 	except:
# 		try:
# 			user = authen.sign_in_with_email_and_password(email,passw)
# 			session_id=user['idToken']
# 			request.session['uid']=str(session_id)
# 		except:
# 			message="invalid credentials"
# 			return render(request,"adx/signIn.html",{"messg":message})
# 	ad_list = []
# 	companyID = email
# 	companyID = companyID.replace('@', '')
# 	companyID = companyID.replace('.', '')
# 	user_zones_keys = database.child("users").child(companyID).child("zones").get()
# 	try:
# 		for ad in user_zones_keys.each():
# 			ad_list.append(database.child('zones').child(ad.val()).get().val())
# 	except:
# 		ad_list = []
# 	name = database.child("users").child(companyID).child('details').child('name').get().val()
# 	status = database.child("users").child(companyID).child('details').child('status').get().val()
# 	return render(request,'adx/index.html', {'context': ad_list, 'name': name, 'status': status})

# def signup(request):
# 	return render(request, "adx/signup.html")

# def postsignup(request):
# 	name=request.POST.get('name')
# 	email=request.POST.get('email')
# 	passw=request.POST.get('pass')
# 	vendor=request.POST.get('vendor')
# 	ID = email.replace('@', '')
# 	ID = ID.replace('.', '')
# 	try:
# 		user=authen.create_user_with_email_and_password(email,passw)
# 	except:
# 		message="Unable to create account try again"
# 		return render(request,"adx/signup.html",{"messg":message})
# 	data={"name":name,"status":vendor}
# 	database.child("users").child(ID).child("details").set(data)
# 	return render(request,"adx/signIn.html")

# def create(request):
# 	return render(request,'adx/create.html')

# from werkzeug.utils import secure_filename

# def post_create(request):
# 	title = request.POST.get('title')
# 	coordinatearea = request.POST.get('coordinate-area')
# 	#enddate = request.POST.get('enddate')
# 	created_on = time.time()
# 	idtoken = request.session['uid']
# 	a = authen.get_account_info(idtoken)
# 	a = a['users']
# 	a = a[0]
# 	companyID = a['email']
# 	companyID = companyID.replace('@', '')
# 	companyID = companyID.replace('.', '')
# 	zoneID = str(companyID) + str(coordinatearea) + str(created_on)
# 	zoneID = zoneID.replace('/', '')
# 	zoneID = zoneID.replace('.', '')
# 	data = {
# 	"title":title,
# 	'coordinatearea':coordinatearea,
# 	'companyID' : companyID,
# 	'zoneID': zoneID,
# 	'created_on' : created_on,
# 	}
# 	ad_list = []
# 	if(coordinatearea==None):
# 		print('no long')
# 	else:
# 		database.child('zones').child(zoneID).set(data)
# 		database.child('users').child(companyID).child('zones').child(zoneID).set(zoneID)
# 	user_zones_keys = database.child("users").child(companyID).child("zones").get()
# 	for ad in user_zones_keys.each():
# 		ad_list.append(database.child('zones').child(ad.val()).get().val())
# 	name = database.child("users").child(companyID).child('details').child('name').get().val()
# 	status = database.child("users").child(companyID).child('details').child('status').get().val()
# 	return render(request,'adx/index.html', {'context': ad_list, 'name': name, 'status': status})

# def log_out(request):
# 	auth.logout(request)
# 	return render(request,'adx/signIn.html')

core/mysite/common/templates/create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb %}

{% endblock breadcrumb %}
{% block content %}
<form id="add_form" method="POST" action="" novalidate>
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-10">
      <div class="card">
        <div class="card-body">
         <div class="card-title text-center">
          CREATE USER
        </div>
          <div class="row marl">
            <div class="col-md-12">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="id_firstname">First Name{% if user_form.first_name.field.required %}<span class="error">*</span>{% endif %}</label>
                  <input type="text" class="form-control" name="first_name" value="{% if user_obj %} {{ user_obj.first_name }} {% else %} {{request.POST.first_name}} {% endif %}">
                </div>
                <span class="error">{{ errors.first_name }}</span>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="id_lastname">Last Name{% if user_form.last_name.field.required %}<span class="error">*</span>{% endif %}</label>
                  <input type="text" class="form-control" name="last_name" value="{% if user_obj %} {{ user_obj.last_name }} {% else %} {{request.POST.last_name}} {% endif %}">
                </div>
                <span class="error">{{ errors.last_name }}</span>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="id_username">Username{% if user_form.username.field.required %}<span class="error">*</span>{% endif %}</label>
                  <input type="text" class="form-control" name="username" value="{% if user_obj %} {{ user_obj.username }} {% else %} {{request.POST.username}} {% endif %}">
                </div>
                <span class="error">{{ errors.username }}</span>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="id_email">Email Address{% if user_form.email.field.required %}<span class="error">*</span>{% endif %}</label>
                  <input type="text" class="form-control" name="email" value="{% if user_obj %} {{ user_obj.email }} {% else %} {{request.POST.email}} {% endif %}" {% if user_obj and not user_obj.is_staff %} readonly=""{% endif %}>
                </div>
                <span class="error">{{ errors.email }}</span>
              </div>
              
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Password{% if user_form.password.field.required %}<span class="error">*</span>{% endif %}</label>
                  <input type="password" class="form-control" name="password" value="{{request.POST.password}}">
                </div>
                <span class="error">{{ errors.password }}</span>
              </div>
              {% endif %}
            </div>
          </div>
          <div class="row marl buttons_row form_btn_row text-center mx-auto" style="text-align: center;">
            <div class="col-12">
            <br>

            <button type="submit" class="btn btn-success mr-2">Submit</button>

            <a href="{% if not user_obj %}{% url 'common:users_list' %}{% else %}{% url 'common:profile' %}{% endif %}" class="btn btn-default clear" id="create_user_cancel" style=" border-radius: 25px;">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock content %}

core/mysite/common/templates/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
  <!-- main_container starts here -->
  <div class="main_container">
    <!-- heading_create starts here -->
    <div class="row marl heading_create">
    <div class="heading col-md-12">
     <div class="no-gutters row">
      <div class="col-8">
        <h1>Users</h1>
      </div>
      <div class="col-4">
        <div class="" style="text-align: right;  margin-bottom: 5%;">
          <button style="max-width: 150px;" class="btn btn-success btn-block ml-auto"><a style="color: white;" href="{% url 'common:create_user'%}"> Add New Client</a></button>
        </div>
      </div>
      </div>
    </div>
  </div>

    <!-- heading_create ends here -->
    <!-- filter_row starts here -->
    <div class="filter_row row marl">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
          <div class="card-title">Filters</div>
          <form id="users_filter" action="" method="POST">
            <div class="row marl">
              <div class="filter_col col-4">
                <div class="form-group">
                  <label for="exampleInputEmail1">User Name</label>
                  <input type="text" class="form-control" placeholder="Username" name="username" value="{{request.POST.username}}">
                </div>
              </div> 
              <div class="filter_col col-4">
                <div class="form-group">
                  <label for="exampleInputEmail1">First Name</label>
                  <input type="text" class="form-control" placeholder="First Name" name="first_name" value="{{request.POST.first_name}}">
                </div>
              </div>
              <div class="filter_col col-4">
                <div class="form-group">
                  <label for="exampleInputEmail1">Email</label>
                  <input type="text" class="form-control" placeholder="Email" name="email" value="{{request.POST.email}}">
                </div>
              </div>
              <div class="filter_col text-center col-12">
                <div class="form-group">
                  <button class="btn btn-primary save" type="submit">Search</button>
                  
                  <a href="{% url 'common:users_list' %}" class="btn btn-default clear">Clear</a>
                </div>
              </div>
              <br clear="all">
            </div>
          </form>
          </div>
        </div>
      </div>
    </div>
    <!-- filter_row ends here -->
    <div class="table_container_row row marl">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="card-title list">
              List of Users
              <span class="float-right total_count">Total Users {{ users|length }}</span>
            </div>
            <div class="table-responsive ">
              <table class="table table-bordered table-striped table-condensed">
                <thead>
                  <tr>
                    <th width="5%" style="text-align:center;">S.No</th>
                    <th width="20%" style="text-align:center;">Username</th>
                    <th width="20%" style="text-align:center;">Email Address</th>
                    <th width="15%" style="text-align:center;">Status</th>
                    <th width="20%" style="text-align:center;">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for user in users %}
                  <tr class="text-center">
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td class="actions">
                      <!-- <a href="{% url 'common:view_user' user.id %}" class="btn btn-info view"><i class="fas fa-eye"></i>View</a> -->
                      <a href="{% url 'common:edit_user' user.id %}" class="btn btn-success edit" style="background-color: #7ED321; border: 0px; color: white; margin-right: 5%;"><i class="fas fa-cogs"></i>
                      <a href="{% url 'common:remove_user' user.id %}" class="btn btn-danger trash" {% if request.user.email == user.email or user.role == "ADMIN" %} style="background-color: #D0021B; border: 0px; color: white; visibility: hidden;" {% endif %}"><i class="fas fa-trash"></i>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            {% ifequal users|length 0 %}
              <h6 class="text-center">No User Records Found</h6>
            {% endifequal %}
            <div class="marl row text-center">
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- main_container ends here -->
{% endblock %}
{% block js_block %}
<script type="text/javascript">
  $('.trash').click(function(e){
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('Are you sure you want to delete?'))
      return;
    window.location = $(this).attr('href')
  });

  $("a[rel='page']").click(function(e){
    e.preventDefault();
    $('#users_filter').attr("action", $(this).attr("href"));
    $('#users_filter').submit();
  });
</script>
{% endblock js_block %}

core/mysite/common/templates/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dasein App</title>
    <!-- Bootstrap core CSS -->

    <link rel="stylesheet" href="{% static 'vendors/iconfonts/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.addons.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/iconfonts/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Custom styling plus plugins -->


    {% block extralinks %}{% endblock %}
</head>
<body class="">
    <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
      <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
        <div class="row w-100">
          <div class="col-lg-4 mx-auto">
            <div class="auto-form-wrapper" style="text-align: center;">
               <!-- <img src="" style="width: 200px;"> -->
               <h1>Dasein</h1>
              <form method="POST" action="" style="text-align: left;">
                <div class="form-group">
                  <label class="label">Username</label>
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Username"  id="exampleInputEmail1"  name="email">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="label">Password</label>
                  <div class="input-group">
                    <input type="password" class="form-control" placeholder="*********"  id="exampleInputPassword1" name="password">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                {% if error %}
                <p>{{ message }}</p>
                {% endif %}
                <div class="form-group">
                  <button type="submit" class="btn btn-primary submit-btn btn-block">Login</button>
                </div>
                <p>Don't have account? <a href="/signup">Sign Up</a></p>
                
              </form>
            </div>
            <ul class="auth-footer">
            <p class="footer-text text-center">copyright © 2018 Dasein. All rights reserved.</p>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>


</body>
<script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'vendors/js/vendor.bundle.addons.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="{% static 'js/off-canvas.js' %}"></script>
  <script src="{% static 'js/misc.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'js/dashboard.js' %}"></script>
  <!-- End custom js for this page-->

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment-with-locales.min.js"></script>
<script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
</html>